service: scrapeogtag-dev
provider:
  name: aws
  runtime: nodejs12.x
functions:
  scrape:
    handler: scrape/controller.scrape
    events:
      - http:
          path: /scrape
          method: post
          integration: lambda
          cors:
            origins:
              - '*'
          response:
            statusCode: 200
            headers:
              Access-Control-Allow-Origin: "*"
              Access-Control-Allow-Credentials: true